# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravity" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "7bdbad8f1c8ffea0a88cf9ddda38803df1084e10cbd792ce3535b9be5ccfbbda"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1ed5cedbc739d6a838087164aae586372e84182b083996dd35175e08b8cde890"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a15651b7cd681b849fad06743b3e7700ea63a23ee9acab3abf84c81d883cf68e"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a211f38e285948020f380cee02027a9f056c219d35d223445c0ad087c62d89d9"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gravity"
  desc "Keeps documentation in Gravity true to your code, from CI"
  homepage "https://github.com/Grupo-Impulso-Digital/gravity-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravity"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravity"]
    end
  end

  # No zap stanza required
end
