# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravity" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "5be12a717d9d1451cafadd8bc417f3578ff3f22f952de2a63cc755d7d0042434"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "17daeb25335c34fe192eae02861110e87366f21492a79f82ae26c08fb0cd0954"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2b23e51b50122b3366e2adec148a83d14c7ec039230f532f7ed905f40052cfd7"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c0a999968c30412e8d4fa899ec09e6b5341cb86029283d3e1df78902b47608f"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gravity"
  desc "Keeps documentation in Gravity true to your code, from CI"
  homepage "https://github.com/Grupo-Impulso-Digital/gravity-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravity"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravity"]
    end
  end

  # No zap stanza required
end
