# This file was generated by GoReleaser. DO NOT EDIT.
cask "gravity" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "4ca97eefad2cb513b6b42ad895a45f73a6b005cb8661dd359cf0bf7ce1344112"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f91360cc7447911e277cf149e2e95e4a32c08de6150ce5e48571d7836aa2be7d"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0f1339789c8060a89132a7083572627dfd843d16573c27e0ab178a9a3fd74570"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4872c85f424e2903f5cb657f78c42aafd11582f2f4d07b916fe1237c6863c870"
      url "https://github.com/Grupo-Impulso-Digital/gravity-cli/releases/download/v#{version}/gravity_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gravity"
  desc "Keeps documentation in Gravity true to your code, from CI"
  homepage "https://github.com/Grupo-Impulso-Digital/gravity-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gravity"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gravity"]
    end
  end

  # No zap stanza required
end
